name: 'Nissuer'
description: 'A GitHub Action for tried and tired maintainers.'
author: 'Balázs Orbán'
branding:
  icon: check-square
  color: orange

inputs:
  reproducition-comment:
    description: 'Either a string or a path to a .md file inside the repository. Example: ".github/invalid-reproduction.md"'
    required: true
  reproduction-hosts:
    description: 'Comma-separated list of hostnames that are allowed for reproductions. Example: "github.com,codesandbox.io"'
    default: github.com
  reproduction-invalid-label:
    description: Label to apply to issues without a valid reproduction.
    default: invalid link
  reproduction-link-section:
    description: 'A regular expression string with "(.*)" matching a valid URL in the issue body. The result is trimmed. Example: "### Link to reproducition(.*)### To reproduce"'
    default: '### Link to reproducition(.*)### To reproduce'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run action
      uses: node20
      run: dist/index.js